name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag node-express-app:latest

      - name: Log in to Docker Hub (or any other registry)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Replace with your Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Replace with your Docker Hub access token

      - name: Push Docker image to Docker Hub (or any other registry)
        run: docker push node-express-app:latest

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run Prisma DB push
        run: docker-compose exec node-express-docker sh -c "npx prisma db push"

      - name: Stop Docker Compose
        run: docker-compose down
